### ISSUE TITLE
Django 1.9 incompatibility

### ISSUE THREAD

**Issue by dchukhin** [caktus/django-scribbler#117]
Importing [django.templates.debug] (https://github.com/caktus/django-scribbler/blob/master/scribbler/forms.py#L9) is a problem, as it [no longer exists](https://github.com/django/django/commit/55f12f8709f0604df7e1817a4c114ead1fb9a311).
Perhaps [Template](https://github.com/django/django/blob/master/django/template/base.py#L170) can be used instead.

**Comment by mlavin** [comment]
Assuming this can now be closed?

**Comment by dchukhin** [comment]
:+1:
