### ISSUE TITLE
Permalink deprecated for Django 2.1

### ISSUE THREAD

**Issue by dpoirier** [caktus/django-scribbler#140]
With deprecation warnings enabled in Django 1.11:

    scribbler/models.py:38: RemovedInDjango21Warning: permalink() is deprecated in favor of calling django.urls.reverse() in the decorated method.

**Comment by PetrDlouhy** [comment]
This is fixed in PR #146, sadly nobody is willing to pull.

**Comment by vkurup** [comment]
Closed in #146
