### ISSUE TITLE
Full Screen/New Window Editing

### ISSUE THREAD

**Issue by mlavin** [caktus/django-scribbler#19]
For large blocks of content it might be helpful to be able to break the editor off into a new window to make it full screen and side-by-side with the content similar to the Chrome developer tools.

**Comment by benred42** [comment]
Codemirror added a fullscreen addon in 3.16 that can accomplish part of that functionality.  It does not break off into a new window, however, so side-by-side wouldn't be supported.

https://codemirror.net/doc/manual.html#addon_fullscreen

**Comment by mlavin** [comment]
Done!
