### ISSUE TITLE
Cannot preview any scribbles without edit or create scribble permission

### ISSUE THREAD

**Issue by kmtracey** [caktus/django-scribbler#48]
If a user does not have permission to edit/add scribbles, but does have permission to edit a field on the page that is in a scribble_field tag, they can bring up the editor for that field, but cannot preview or save any changes.

Preview view is checking specifically for the scribbler.change_scribble and scribbler.add_scribble permissions. If the user does not have one of those, forbidden is returned. If the preview does not succeed, save is not allowed.

Possible ways to fix:

1 - Expand information POSTed to preview to include the actual model being edited, and have preview check for permissions on that model instead of hard-coding the scribbler model.

2 - Remove permission checking from preview. Preview isn't actually making any changes so why does it need to check for the permission to do so? Ultimately the save will fail if the user really does not have permission to save what they are previewing.

3 - Require that the user must have scribble field permissions even when editing non-scribble fields. This would need to be noted in doc and enforced in scribble_field tag and save view.

I'm leaning towards option 2...it's easiest and I don't see why preview needs to be doing permission checking?

**Comment by jbradberry** [comment]
@mlavin @kmtracey given these concerns, would you say that option 1) is the reasonable way to go here?

**Comment by kmtracey** [comment]
@jbradberry sure!
