### ISSUE TITLE
Django 1.8 Compatibility

### ISSUE THREAD

**Issue by mlavin** [caktus/django-scribbler#84]
Django 1.8 adds support for multiple template engines. Some of the APIs for loading templates have been adjusted to handle this. In particular creating an instance of a template (which is done in `scribbler_tags` and when rendering the preview) will only work if only the Django template engine is enabled. The upgrade notes don't include a clear alternative if that isn't the case.

**Comment by benred42** [comment]
This appears to have been mostly addressed in #86 and #94.  What work, if any remains to be done on this issue?

**Comment by mlavin** [comment]
Yes I think this is can be closed.
