### ISSUE TITLE
Tox File Needs Updating

### ISSUE THREAD

**Issue by benred42** [caktus/django-scribbler#90]
Tox file out of date.  Can be cleaned up using newer generative envlist format.

**Comment by benred42** [comment]
It looks like we're currently supporting Python 2.6, 2.7, 3.2 and Django 1.3 - 1.8.  I assume we want to include Python 3.3 and 3.4, but do we want to drop support for any of the older Python/Django releases?

**Comment by mlavin** [comment]
Python 2.6 is not supported on Django 1.7+. I'd like to drop support for Django < 1.7 (and hence the old South migrations) but I think we should get a stable release with 1.8 support out first.
